// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpS2uISlNEk0azhbznbSl2MpoQ3SvbD0s',
    appId: '1:755755755750:web:8fe27cfa5e2b7b37ea3327',
    messagingSenderId: '755755755750',
    projectId: 'weather-app-flutter-e7536',
    authDomain: 'weather-app-flutter-e7536.firebaseapp.com',
    storageBucket: 'weather-app-flutter-e7536.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQJ9xqtW8M4Zbv77V6PnjOk7jOKs_oec',
    appId: '1:755755755750:android:2e7cca01d35478efea3327',
    messagingSenderId: '755755755750',
    projectId: 'weather-app-flutter-e7536',
    storageBucket: 'weather-app-flutter-e7536.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqbG4xV_fg4aJbWW-h13XSL7ta3ozrsqM',
    appId: '1:755755755750:ios:b2e98791243dbc4fea3327',
    messagingSenderId: '755755755750',
    projectId: 'weather-app-flutter-e7536',
    storageBucket: 'weather-app-flutter-e7536.appspot.com',
    iosClientId: '755755755750-8bsb3srhjq0g6mcgdmgnegf37tf33v61.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseSimple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqbG4xV_fg4aJbWW-h13XSL7ta3ozrsqM',
    appId: '1:755755755750:ios:b780f7e91b6776bbea3327',
    messagingSenderId: '755755755750',
    projectId: 'weather-app-flutter-e7536',
    storageBucket: 'weather-app-flutter-e7536.appspot.com',
    iosClientId: '755755755750-1rjpipf5nroc4odk8rbud2erb588cm37.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseSimple.RunnerTests',
  );
}
